version: 0.2

env:
  variables:
    NODE_ENV: production
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - export API_REPOSITORY_URL="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vic-ia"
      - export GIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - >
        aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker pull $API_REPOSITORY_URL:latest || true
  build:
    commands:
      - set -e
      - cd backend
      - yarn install
      - yarn list --pattern tsconfig
      - yarn why tsconfig-paths
      - yarn run build
      - >
        docker build
        --cache-from $API_REPOSITORY_URL:latest
        --tag $API_REPOSITORY_URL:$GIT_HASH
        -f Dockerfile .
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - docker push $API_REPOSITORY_URL --all-tags
      - >
        printf '[{"name":"API","imageUri":"%s"}]'
        "$API_REPOSITORY_URL:$GIT_HASH" >
        imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

