services:
  back:
    image: node:20-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      ENV: '${NODE_ENV:-development}'
      OPENAI_ORGANIZATION: '${OPENAI_ORGANIZATION}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      COWMED_API_URL: '${COWMED_API_URL}'
      YARN_VERSION: '4.1.1'
      AXIOS_CA: '/ca.crt'
      PORT: '3001'
    working_dir: '/home/node/app'
    ports:
      - '${PORT:-3001}:3001'
    volumes:
      - './backend:/home/node/app'
      - '${AXIOS_CA}:/ca.crt'
    command: ['yarn', 'run', 'dev']
