services:
  back:
    image: node:20-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${VITE_COWMED_API_URL}:host-gateway'
    environment:
      ENV: '${NODE_ENV:-development}'
      OPENAI_ORGANIZATION: '${OPENAI_ORGANIZATION}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      OPENAI_ASSISTANT: '${OPENAI_ASSISTANT}'
      GEMINI_API_KEY: '${GEMINI_API_KEY}'
      COWMED_API_URL: '${COWMED_API_URL}'
      LLM_BACKEND: '${LLM_BACKEND}'
      DYNAMODB_ENDPOINT: '${DYNAMODB_ENDPOINT:-http://dynamodb:8000}'
      YARN_VERSION: '4.1.1'
      AXIOS_CA: '/ca.crt'
      PORT: '3001'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    working_dir: '/home/node/app'
    ports:
      - '${PORT:-3001}:3001'
    volumes:
      - './backend:/home/node/app'
      - '${AXIOS_CA}:/ca.crt'
    command: ['yarn', 'run', 'dev']
    depends_on:
      - dynamodb
  front:
    image: node:20-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      ENV: '${NODE_ENV:-development}'
      VITE_LOG_VERBOSITY: '${VITE_LOG_VERBOSITY}'
      VITE_COWMED_AUTH_URL: '${VITE_COWMED_AUTH_URL}'
      VITE_COWMED_API_URL: '${VITE_COWMED_API_URL}'
      VITE_COWMED_OAUTH_CLIENT_ID: '${VITE_COWMED_OAUTH_CLIENT_ID}'
      VITE_BACKEND_HOST: 'http://127.0.0.1:${PORT:-3001}'
      VITE_WEBSOCKET_HOST: 'ws://127.0.0.1:${PORT:-3001}'
    working_dir: '/home/node/app'
    ports:
      - '5173:5173'
    volumes:
      - './:/home/node/app'
    command: ['yarn', 'run', 'dev', '--host']
    depends_on:
      - back
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: vic-dynamodb
    volumes:
      - "./docker/dynamodb/data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    ports:
      - "7998:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -d '{}' -sSf -m 3 --user 'A:A' --aws-sigv4 'aws:amz:sa-east-1:dynamodb' -H 'X-Amz-Target: DynamoDB_20120810.ListTables' -o /dev/null 127.0.0.1:8000"]
      retries: 3
      timeout: 2s
